test: Updates `test_get_smtp_handler`
If this test went before other loggers the following was raised:
`AttributeError: 'Recorder' object has no attribute 'level'`

Test no longer effects global state of `app.logger`